### ISSUE TITLE
Tool Not working in Arc 10.5 for TomTom processing

### ISSUE THREAD

**Issue by cclukey** [Esri/street-data-processing-tools#14] opened 2017-05-01 19:21 UTC
ERROR -1
Field named MINUTES is not the expected type. This pertains to "Input Network Geometry (NW) Feature Class".

**Comment by cclukey** [comment] 2017-05-01 19:25
This pertains to "Input Network Geometry (NW) Feature Class".

**Comment by BWsGit** [comment] 2017-05-01 20:03
Was the FGDB that holds the TomTom source data created using an earlier version than 10.5? That was our problem when we were receiving these errors. I think we were using 10.2 to create the FGDB, and the integer fields appeared as integer fields when I checked using that software. But when I checked the field type using versions 10.3 or higher the integer fields appeared as double.

**Comment by cclukey** [comment] 2017-05-01 20:15
Most likely but i will have to look at documentation as the data I am referencing is sample data from a vendor.

What are the data types for those fields (meters and minutes) supposed to be?

**Comment by BWsGit** [comment] 2017-05-01 20:22
It looks like Meters should be double and Minutes should be float. My problem was strictly integer coming through as double, so maybe this isn't the same issue, but at least worth taking a look to rule it out.

**Comment by cclukey** [comment] 2017-05-02 19:39
What is the best way to change the data type? I can only change the number format.

**Comment by BWsGit** [comment] 2017-05-02 19:54
You can change the data type of a field. You need to add a new field of the correct data type, populate the new field with the field calculator tool, delete the original field, and change the name of the new field to the  name of the original field. I had several feature classes each with several integer fields, so I wrote script to automate this until we figured out the root cause of the problem.

**Comment by cclukey** [comment] 2017-05-02 20:02
I was able to change the data type and the error went away; however, the tool failed to execute saying the tool is not valid - ERROR 000816.

**Comment by cclukey** [comment] 2017-05-04 13:23
Has anyone had success with these tools in 10.5?

**Comment by cclukey** [comment] 2017-05-04 17:38
4/4/2017 UPDATE:

I was able to get the tool to run, but it failed to execute. Below are the details...

Executing: ProcessMultiNetData "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________nw.shp" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mp.dbf" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________si.dbf" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________sp.dbf" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb" 10.1 Routing Routing_ND false false "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________rs.dbf" # # # # # # # # # # # # #
Start Time: Thu May 04 13:22:55 2017
Creating the file geodatabase and feature dataset...
Executing: CreateFileGDB "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP" Chicago.gdb 9.3
Start Time: Thu May 04 13:22:57 2017
Succeeded at Thu May 04 13:22:58 2017 (Elapsed Time: 1.17 seconds)
Executing: CreateFeatureDataset "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb" Routing "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 11258999068426.2;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision"
Start Time: Thu May 04 13:23:03 2017
Succeeded at Thu May 04 13:23:04 2017 (Elapsed Time: 1.51 seconds)
Executing: MakeFeatureLayer "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________nw.shp" nw_Layer "FEATTYP <> 4165" # "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;ID ID VISIBLE NONE;FEATTYP FEATTYP VISIBLE NONE;FT FT VISIBLE NONE;F_JNCTID F_JNCTID VISIBLE NONE;F_JNCTTYP F_JNCTTYP VISIBLE NONE;T_JNCTID T_JNCTID VISIBLE NONE;T_JNCTTYP T_JNCTTYP VISIBLE NONE;PJ PJ VISIBLE NONE;METERS METERS VISIBLE NONE;FRC FRC VISIBLE NONE;NETCLASS NETCLASS VISIBLE NONE;NETBCLASS NETBCLASS VISIBLE NONE;NET2CLASS NET2CLASS VISIBLE NONE;NAME NAME VISIBLE NONE;NAMELC NAMELC VISIBLE NONE;SOL SOL VISIBLE NONE;NAMETYP NAMETYP VISIBLE NONE;CHARGE CHARGE VISIBLE NONE;SHIELDNUM SHIELDNUM VISIBLE NONE;RTETYP RTETYP VISIBLE NONE;RTEDIR RTEDIR VISIBLE NONE;RTEDIRVD RTEDIRVD VISIBLE NONE;PROCSTAT PROCSTAT VISIBLE NONE;FOW FOW VISIBLE NONE;SLIPRD SLIPRD VISIBLE NONE;FREEWAY FREEWAY VISIBLE NONE;BACKRD BACKRD VISIBLE NONE;TOLLRD TOLLRD VISIBLE NONE;RDCOND RDCOND VISIBLE NONE;STUBBLE STUBBLE VISIBLE NONE;PRIVATERD PRIVATERD VISIBLE NONE;CONSTATUS CONSTATUS VISIBLE NONE;ONEWAY ONEWAY VISIBLE NONE;F_BP F_BP VISIBLE NONE;T_BP T_BP VISIBLE NONE;F_ELEV F_ELEV VISIBLE NONE;T_ELEV T_ELEV VISIBLE NONE;KPH KPH VISIBLE NONE;POSACCUR POSACCUR VISIBLE NONE;CARRIAGE CARRIAGE VISIBLE NONE;LANES LANES VISIBLE NONE;RAMP RAMP VISIBLE NONE;ADA ADA VISIBLE NONE;TRANS TRANS VISIBLE NONE;DYNSPEED DYNSPEED VISIBLE NONE;SPEEDCAT SPEEDCAT VISIBLE NONE;NTHRUTRAF NTHRUTRAF VISIBLE NONE;ROUGHRD ROUGHRD VISIBLE NONE;PARTSTRUC PARTSTRUC VISIBLE NONE;MINUTES MINUTES VISIBLE NONE"
Start Time: Thu May 04 13:23:05 2017
Succeeded at Thu May 04 13:23:05 2017 (Elapsed Time: 0.11 seconds)
Importing and spatially sorting the Streets feature class...
Executing: Sort nw_Layer "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing\Streets" "Shape #" PEANO
Start Time: Thu May 04 13:23:09 2017
Succeeded at Thu May 04 13:24:04 2017 (Elapsed Time: 54.78 seconds)
Executing: Delete nw_Layer #
Start Time: Thu May 04 13:24:05 2017
Succeeded at Thu May 04 13:24:05 2017 (Elapsed Time: 0.01 seconds)
Indexing the ID field...
Executing: AddIndex "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing\Streets" ID ID NON_UNIQUE NON_ASCENDING
Start Time: Thu May 04 13:24:05 2017
Succeeded at Thu May 04 13:24:10 2017 (Elapsed Time: 4.68 seconds)
Copying the Maneuvers feature class and indexing...
Executing: FeatureClassToFeatureClass "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb" mn # "ID "ID" true true false 15 Double 0 15 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp,ID,-1,-1;FEATTYP "FEATTYP" true true false 4 Short 0 4 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp,FEATTYP,-1,-1;BIFTYP "BIFTYP" true true false 1 Short 0 1 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp,BIFTYP,-1,-1;PROMANTYP "PROMANTYP" true true false 1 Short 0 1 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp,PROMANTYP,-1,-1;JNCTID "JNCTID" true true false 15 Double 0 15 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mn.shp,JNCTID,-1,-1" #
Start Time: Thu May 04 13:24:11 2017
Succeeded at Thu May 04 13:24:13 2017 (Elapsed Time: 2.20 seconds)
Executing: AddIndex "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mn" ID ID NON_UNIQUE NON_ASCENDING
Start Time: Thu May 04 13:24:13 2017
Succeeded at Thu May 04 13:24:14 2017 (Elapsed Time: 0.21 seconds)
Copying the Maneuver Path table...
Executing: TableToTable "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mp.dbf" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb" mp # "ID "ID" true true false 15 Double 0 15 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mp.dbf,ID,-1,-1;SEQNR "SEQNR" true true false 5 Long 0 5 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mp.dbf,SEQNR,-1,-1;TRPELID "TRPELID" true true false 15 Double 0 15 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mp.dbf,TRPELID,-1,-1;TRPELTYP "TRPELTYP" true true false 4 Short 0 4 ,First,#,W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago37\usauxx________mp.dbf,TRPELTYP,-1,-1" #
Start Time: Thu May 04 13:24:14 2017
Succeeded at Thu May 04 13:24:20 2017 (Elapsed Time: 5.75 seconds)
Creating and calculating fields for the maneuver types and at junctions...
Executing: AddField "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mp" JNCTID DOUBLE # # # # NULLABLE NON_REQUIRED #
Start Time: Thu May 04 13:24:21 2017
Adding JNCTID to W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mp...
Succeeded at Thu May 04 13:24:21 2017 (Elapsed Time: 0.07 seconds)
Executing: AddField "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mp" FEATTYP SHORT # # # # NULLABLE NON_REQUIRED #
Start Time: Thu May 04 13:24:21 2017
Adding FEATTYP to W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mp...
Succeeded at Thu May 04 13:24:22 2017 (Elapsed Time: 0.08 seconds)
Executing: MakeTableView "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mp" mp_View # # "OBJECTID OBJECTID VISIBLE NONE;ID ID VISIBLE NONE;SEQNR SEQNR VISIBLE NONE;TRPELID TRPELID VISIBLE NONE;TRPELTYP TRPELTYP VISIBLE NONE;JNCTID JNCTID VISIBLE NONE;FEATTYP FEATTYP VISIBLE NONE"
Start Time: Thu May 04 13:24:23 2017
Succeeded at Thu May 04 13:24:23 2017 (Elapsed Time: 0.06 seconds)
Executing: AddJoin mp_View ID "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\mn" ID KEEP_ALL
Start Time: Thu May 04 13:24:24 2017
Succeeded at Thu May 04 13:24:24 2017 (Elapsed Time: 0.06 seconds)
Executing: CalculateField mp_View mp.JNCTID [mn.JNCTID] VB #
Start Time: Thu May 04 13:24:24 2017
Succeeded at Thu May 04 13:28:44 2017 (Elapsed Time: 4 minutes 19 seconds)
Executing: CalculateField mp_View mp.FEATTYP [mn.FEATTYP] VB #
Start Time: Thu May 04 13:28:44 2017
Succeeded at Thu May 04 13:33:20 2017 (Elapsed Time: 0.46 seconds)
Creating turn feature class...
Executing: Statistics "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\ProhibMPwJnctID" "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\tempStatsTable" "SEQNR MAX" #
Start Time: Thu May 04 13:33:22 2017
Succeeded at Thu May 04 13:33:23 2017 (Elapsed Time: 1.51 seconds)
Executing: CreateTurnFeatureClass "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing" RestrictedTurns 6 # "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\TheTemplate" # # 0 0 0 DISABLED
Start Time: Thu May 04 13:33:26 2017
Succeeded at Thu May 04 13:33:30 2017 (Elapsed Time: 3.91 seconds)
Updating the Edge1End values...
Executing: MakeFeatureLayer "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing\RestrictedTurns" Turn_Layer # # "OBJECTID OBJECTID VISIBLE NONE;SHAPE SHAPE VISIBLE NONE;Edge1End Edge1End VISIBLE NONE;Edge1FCID Edge1FCID VISIBLE NONE;Edge1FID Edge1FID VISIBLE NONE;Edge1Pos Edge1Pos VISIBLE NONE;Edge2FCID Edge2FCID VISIBLE NONE;Edge2FID Edge2FID VISIBLE NONE;Edge2Pos Edge2Pos VISIBLE NONE;Edge3FCID Edge3FCID VISIBLE NONE;Edge3FID Edge3FID VISIBLE NONE;Edge3Pos Edge3Pos VISIBLE NONE;Edge4FCID Edge4FCID VISIBLE NONE;Edge4FID Edge4FID VISIBLE NONE;Edge4Pos Edge4Pos VISIBLE NONE;Edge5FCID Edge5FCID VISIBLE NONE;Edge5FID Edge5FID VISIBLE NONE;Edge5Pos Edge5Pos VISIBLE NONE;Edge6FCID Edge6FCID VISIBLE NONE;Edge6FID Edge6FID VISIBLE NONE;Edge6Pos Edge6Pos VISIBLE NONE;AltID1 AltID1 VISIBLE NONE;AltID2 AltID2 VISIBLE NONE;AltID3 AltID3 VISIBLE NONE;AltID4 AltID4 VISIBLE NONE;AltID5 AltID5 VISIBLE NONE;AltID6 AltID6 VISIBLE NONE;ID ID VISIBLE NONE;JNCTID JNCTID VISIBLE NONE;SHAPE_Length SHAPE_Length VISIBLE NONE"
Start Time: Thu May 04 13:33:33 2017
Succeeded at Thu May 04 13:33:33 2017 (Elapsed Time: 0.07 seconds)
Executing: AddJoin Turn_Layer AltID1 "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing\Streets" ID KEEP_ALL
Start Time: Thu May 04 13:33:33 2017
Succeeded at Thu May 04 13:33:33 2017 (Elapsed Time: 0.03 seconds)
Executing: CalculateField Turn_Layer RestrictedTurns.Edge1End x VB "Select Case [RestrictedTurns.JNCTID]\n  Case [Streets.F_JNCTID]: x = "N"\n  Case [Streets.T_JNCTID]: x = "Y"\n  Case Else: x = "?"\nEnd Select"
Start Time: Thu May 04 13:33:33 2017
Succeeded at Thu May 04 13:33:40 2017 (Elapsed Time: 6.81 seconds)
Executing: RemoveJoin Turn_Layer Streets
Start Time: Thu May 04 13:33:40 2017
Succeeded at Thu May 04 13:33:40 2017 (Elapsed Time: 0.02 seconds)
Executing: Delete Turn_Layer #
Start Time: Thu May 04 13:33:41 2017
Succeeded at Thu May 04 13:33:41 2017 (Elapsed Time: 0.00 seconds)
Updating the EdgeFID values...
Executing: UpdateByAlternateIDFields "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing\Streets" ID
Start Time: Thu May 04 13:33:50 2017
ERROR 999999: Error executing function.
The value for the Edge1End field in the turn feature class is invalid.
Failed to execute (UpdateByAlternateIDFields).
Failed at Thu May 04 13:33:52 2017 (Elapsed Time: 1.92 seconds)
Executing: UpdateByAlternateIDFields "W:\NZ\Planning and Business Developement\BP\Maps\Street Networks\TomTom MultiNet Street Data Sample - SHP\Chicago.gdb\Routing\Streets" ID
Start Time: Thu May 04 13:33:50 2017
ERROR 999999: Error executing function.
The value for the Edge1End field in the turn feature class is invalid.
Failed to execute (UpdateByAlternateIDFields).
Failed at Thu May 04 13:33:52 2017 (Elapsed Time: 1.92 seconds)
Error HRESULT E_FAIL has been returned from a call to a COM component.
   at ESRI.ArcGIS.Geoprocessing.GeoProcessorClass.Execute(String Name, IVariantArray ipValues, ITrackCancel pTrackCancel)
   at ESRI.ArcGIS.Geoprocessor.Geoprocessor.ExecuteInner(IGPProcess process, ITrackCancel trackCancel, IGeoProcessor igp, IVariantArray iva)
   at ESRI.ArcGIS.Geoprocessor.Geoprocessor.Execute(IGPProcess process, ITrackCancel trackCancel)
   at GPProcessVendorDataFunctions.ProcessMultiNetDataFunction.CreateAndPopulateTurnFeatureClass(String outputFileGdbPath, String fdsName, String ProhibMPTableName, String tempStatsTableName, IGPMessages messages, ITrackCancel trackcancel)
   at GPProcessVendorDataFunctions.ProcessMultiNetDataFunction.Execute(IArray paramvalues, ITrackCancel trackcancel, IGPEnvironmentManager envMgr, IGPMessages messages)
Failed to execute (ProcessMultiNetData).
Failed at Thu May 04 13:33:53 2017 (Elapsed Time: 10 minutes 58 seconds)

**Comment by daanhub** [comment] 2017-05-22 11:45
I'm also experiencing this problem. 
I would be for ever grateful if a fix would occur :)

**Comment by speerwerperKevin** [comment] 2017-06-26 15:30
same kind of problem here, this time for the HSPR table: (TIME_SLOT is not the expected type). Changing the data type indeed generates a 'failed to execute' error later on..

**Comment by aHatakeyama** [comment] 2018-03-20 18:12
Regarding the issue that @cclukey raised with invalid Edge1End values, this may be due to the result that your maneuvers in the MN and MP tables span more than the streets in your NW feature class.

**Comment by nicogis** [comment] 2018-08-02 15:41
@cclukey if you have this error: "

> The value for the Edge1End field in the turn feature class is invalid

"
in this row https://github.com/Esri/street-data-processing-tools/blob/3903d2d163792c39458bd7d29f4b94972ce6541e/ProcessMultiNetDataFunction.cs#L2652

tool sets with a dummy value ("?") field Edge1End but this field can have Y or N value so after for problems on data you can have rows with value '?' in field Edge1End and tool UpdateByAlternateIDFields throws a error.
So peraphs in code after this row https://github.com/Esri/street-data-processing-tools/blob/3903d2d163792c39458bd7d29f4b94972ce6541e/ProcessMultiNetDataFunction.cs#L2744
could be remove the rows with value '?' in field Edge1End  or showed a warning of rows with '?' because UpdateByAlternateIDFields throws error...

**Comment by mmorang** [comment] 2024-06-06 14:21
There have been no updates to this thread since 2018.  We released a fully rewritten version of the Street Data Processing Tools for processing TomTom data in ArcGIS Pro several years ago and haven't gotten reports of any similar problems.  I'm going to close this issue.  If you encounter a similar problem with the Pro version of the tool, please open a new issue.

**Closed by mmorang** 2024-06-06 14:21 UTC
