### ISSUE TITLE
Tool won't run because of Error for Link_ID field data types for the feature classes and tables

### ISSUE THREAD

**Issue by dscottibm** [Esri/street-data-processing-tools#39] opened 2021-03-25 13:45 UTC
I am trying to run Street Data Processing Tools v10.6.0.3 on Here data acquired on 2020/11/30 and the tool fails to read the Data from the Link_ID Field and will not run. My build is windows 10 and ArcGIS 10.6.1.

<img width="440" alt="StreetDataProcessingToolErrorwithHereData" src="https://user-images.githubusercontent.com/81368516/112482361-98bd5b00-8d3d-11eb-8669-5d7e6ee01f91.PNG">

Any idea why it doesn't like the long integer data type for this field? It appears that all the data used in the tool has the data type for this field. And is there a fix for this issue?  I have tried changing the data type and the data will not load into a short integer field data type.

**Comment by deelesh** [comment] 2021-03-30 13:28
@dscottibm 
I am unable to reproduce the error on my end. We also released a [newer version](https://github.com/Esri/street-data-processing-tools/releases/tag/v10.8.0.1) (v10.8.0.1) that works with ArcGIS Desktop 10.8 or later. If you have access to ArcGIS 10.8  or ArcGIS 10.8.1, Can you try with that version?

**Comment by dscottibm** [comment] 2021-03-30 17:48
Can you tell me what data you are using. I have the latest release of the Here Data. do you know of any issues with that newer data and the 10.6.1 tools that we are trying to use? Any chance I can do a screen share with you? I is possible to contact you via Esri support?

**Comment by geraldine0** [comment] 2021-04-15 15:16
I had the same issue with version 10.6.0.3 and data acquired today. As mentioned in [this post](https://github.com/Esri/street-data-processing-tools/issues/22) the field precision was the issue. Specs say field format should be INTEGER(3) and field was a Long Integer - precision 6. I created temporary fields to hold the field values, deleted the original fields and added new fields  with the same name - short integers with correct precision (3), and copied the values from the temporary fields there. Tedious, but Alter Field won't work with shapefiles. After that the tool ran, without error.

**Comment by dscottibm** [comment] 2021-04-15 19:29
Ok thanks I'll try that Did you try it on a file GeoDatabase?

**Comment by dscottibm** [comment] 2021-04-15 21:19
I have tried to copy and also Calc the values from the original field Long integer field (Min is 10 Characters) and it won't let them come over to the short integer field with a precision of 3? Wondering how you forced that data into there?

**Comment by geraldine0** [comment] 2021-04-16 05:38
I'm using TomTom data (shapefiles). Issues occurred with other tables (speed profiles) and other fields. All values could fit into the short fields with precision 3. Maybe your fields have a different precision? You should check the specs. I suspect a short integer(3) is not enough for an ID field.

**Comment by dscottibm** [comment] 2021-04-16 13:41
I am using Here data the field precision that comes in the data is 10 and is populated with 8, I am unable to force it to the precision of 3? Have tried several ways (Field Calc and copy and paste) to get the data in a new filed with that precision of 3 but it won't take it. So I'm still stuck not getting this tool to run.

**Comment by dscottibm** [comment] 2021-05-06 14:37
I have gotten the latest version of the ArcGIS and the street-data-processing-tool and I no longer have the data type issue but now I get the Error that "the tool is not valid". Not sure what to do to fix this?

**Comment by sirri050** [comment] 2021-12-29 16:26
I was able to run the HERE Data Processing Tool after being stuck for a while.

I changed the LINK_ID Field type to Long Integer, with a precision of 10, and from (Numeric) tab, I changed the number of significant digits to the max value in field data, which was 10.

For SEQ_NUMBER and SEQ_NUM fields, Short Integer with a precision of 2 is enough, as per the values in the fields.

I did that on all applicable StreetsPrj, AltStreetsPrj, and ZlevelsPrj FCs, and Cdms, Rdms, and Signs Tables.

However, the LINK_ID wasn’t the only field that produces the error. Every time you modify a field, other fields with the same field type errors come up. You will get errors from SRC_LINKID, MAN_LINKID, Sign_ID, SEQ_NUMBER, and SEQ_NUM fields on the different FCs and tables. So you have to modify each one then try to run the tool, till there is no error.

To change the field type, you have to add a new field > use the Field Calculator to populate it, delete the original field, then (if unable to rename it) add a new field with the original name and calculate it as well.
![HERE_tool](https://user-images.githubusercontent.com/50466663/147683137-8055d5b0-33c4-439c-9ad4-aa126c4912ad.png)
![HERE_tool_running](https://user-images.githubusercontent.com/50466663/147683141-0ad00257-9542-4871-aa4e-9875725fce29.png)

**Comment by sirri050** [comment] 2022-09-27 13:52
> I have gotten the latest version of the ArcGIS and the street-data-processing-tool and I no longer have the data type issue but now I get the Error that "the tool is not valid". Not sure what to do to fix this?

You need to download the latest HERE Data Processing tool. I am using v10.8.1

**Comment by mmorang** [comment] 2024-06-06 14:59
I apologize for the troubles that everyone in this thread has had with field types in the HERE data.  It seems from this thread and several other issues logged by other users that this was a common problem.  I'm not sure whether it's still an issue.

A new version of the Street Data Processing Tools for processing HERE data in ArcGIS Pro is now available.  If you're still processing HERE data, please try the new version of the tool and let us know if you're still experiencing problems with field type checks failing.  We may be able to address it more easily in the new version of the tool.

**Comment by mmorang** [comment] 2024-09-09 14:19
It's been three months, and there have been no further comments on this issue, so I'm closing it.  If you're still having problems, feel free to re-open.

**Closed by mmorang** 2024-09-09 14:19 UTC
